# Generated by Django 2.2.5 on 2021-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoesize',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
